server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  sleuth:
    jdbc:
      p6spy:
        enable-logging=true:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/*