grant_type:client_credentials
client_id:oP84kHwhuq3vsDghv9RHu8ITylpvGHJo
client_secret:9Fc7eEU4OvHAbD8C4RXj3iPJyjkWnP40
dsAuthApiUrl:https://gateway.optum.com
server.port:9922

api-registry:
  socketTimeout: 30
  readTimeout: 30
  writeTimeout: 30
  retryTimeout: 100
  stargateConfig:
    env:
      DMZ_PUBLIC_STAGE: https://gateway-stage.optum.com
      CORE_STAGE: https://gateway-stage-core.optum.com
      CORE_PROD: https://gateway-core.optum.com
    clientId: 4bJo181ECbr1vbJFciUN0PeqZBlUqNBG
    clientSecret: VeRE8BhI7iAJuMTZT3IyFe7yQgWG3aR2
    tokenPath: auth/oauth2/cached/token
  registrations:
    digitalSecurity:
      stargateEnv: DMZ_PUBLIC_STAGE
      apis:
        dsOrgAPIURL:
          url: api/stage/pdr/ds/access/org/v1.0
        dsTinAPIURL:
          url: api/stage/pdr/ds/access/tin/v1.0
        dsProviderAPIURL:
          url: api/stage/pdr/ds/access/provider/v1.0
    shield:
      stargateEnv: CORE_STAGE
      apis:
        addressApi:
          url: api/testbravouat/pdr/shield/place-of-services/v1/search
        primaryCareMemberAPI:
          url: api/testalphauat/pdr/shield/primary-care-members/v1/search
        providersSearchOnTin:
          url: api/testalphauat/pdr/shield/providers/v3/search